---
- name: Create projects
  hosts: localhost
  become: false
  gather_facts: false

  vars:
    project_dir: "{{ dir | default('./ansible_project') }}"
    with_collections_flag: "{{ with_collections | default(false) | bool }}"

  tasks:

    - name: Create the standard project directories
      ansible.builtin.file:
        path: "{{ project_dir }}/{{ item }}"
        state: directory
        mode: 0755
      loop:
        - inventory/group_vars
        - inventory/host_vars
        - playbooks
        - plugins/filters
        - plugins/modules
        
    - name: Create roles project_directory in the project root
      ansible.builtin.file:
        path: "{{ project_dir }}/roles"
        state: directory
        mode: 0755
      when: not with_collections_flag

    - name: Setup collections structure
      when: with_collections_flag
      block:

          - name: Collections project_directory
            ansible.builtin.file:
              path: "{{ project_dir }}/collections/ansible_collections"
              state: directory
              mode: 0755

          - name: Create requirements file
            ansible.builtin.copy:
              dest: "{{ project_dir }}/collections/requirements.yaml"
              content: |
                collections:
                  - name: ansible.posix
                  - name: community.general
         
    - name: Create project Ansible configuration
      ansible.builtin.copy:
        dest: "{{ project_dir }}/ansible.cfg"
        content: |
          [defaults]
          remote_user = ansible
          host_key_checking = false
          {% if with_collections_flag %}
          collections_paths = ./collections
          {% endif %}
          {% if not with_collections_flag %}
          roles_path = ./roles
          {% endif %}


